name: Daily DV Lottery Check

on:
  schedule:
    - cron: '0 9 * * *'  # runs daily at 9:00 UTC
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      EMAIL_SUBJECT: ${{ secrets.EMAIL_SUBJECT }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run DV checker
        run: python check_dv.py
